# ==============================================================================
# Local LLM to Robomotion Bridge (CLI Version)
# Copyright (C) 2026 Thexoxo (https://github.com/Thexoxo)
# YouTube: https://www.youtube.com/@xoxoPwn
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License.
# ==============================================================================

import os
import subprocess
import shutil
import json
import urllib.request
import urllib.error
import urllib.parse
import argparse
from pathlib import Path

def create_github_repo(username, pat, repo_name):
    url = "https://api.github.com/user/repos"
    headers = {
        "Authorization": f"Bearer {pat}",
        "Accept": "application/vnd.github.v3+json",
        "User-Agent": "Local-LLM-to-Robomotion-Bridge"
    }
    data = {
        "name": repo_name,
        "private": True,
        "description": "RPA Workspace generated by Local-LLM-to-Robomotion Bridge"
    }
    
    req = urllib.request.Request(url, data=json.dumps(data).encode("utf-8"), headers=headers, method="POST")
    try:
        with urllib.request.urlopen(req) as response:
            res_data = json.loads(response.read().decode())
            return res_data["clone_url"]
    except urllib.error.HTTPError as e:
        if e.code == 422:
            return f"https://github.com/{username}/{repo_name}.git"
        raise Exception(f"GitHub API Error: {e.code} - {e.reason}")

def setup_workspace(project_name, username, pat):
    project_name_clean = project_name.replace(" ", "-")
    
    print(f"[*] Contacting GitHub API to create repository '{project_name_clean}'...")
    try:
        repo_url = create_github_repo(username, pat, project_name_clean)
        print(f"[+] Repository ready: {repo_url}")
    except Exception as e:
        print(f"[!] Error creating GitHub repository: {e}")
        return

    desktop = Path(os.path.expanduser("~")) / "Desktop"
    workspace = desktop / project_name_clean
    script_dir = Path(__file__).parent
    source_docs = script_dir / 'skills-fallback'
    
    workspace.mkdir(parents=True, exist_ok=True)
    print(f"[*] Created local workspace at: {workspace}")
    
    dest_skills = workspace / "skills-fallback"
    if source_docs.exists() and not dest_skills.exists():
        shutil.copytree(source_docs, dest_skills)
        print("[+] Copied Robomotion documentation (skills-fallback).")
    elif not source_docs.exists():
        print("[!] Warning: 'skills-fallback' folder not found. AI will lack documentation.")
        
    template_path = script_dir / 'prompt_template.md'
    dest_prompt = workspace / "agent_rules.md"
    if template_path.exists():
        shutil.copy2(template_path, dest_prompt)
        print("[+] Copied agent_rules.md")
    else:
        print("[!] Warning: prompt_template.md not found.")
        
    with open(workspace / "main.ts", "w", encoding="utf-8") as f:
        f.write("import { flow, Message, Custom, JS, Global, Flow, Credential, AI } from '@robomotion/sdk';\n\nconst myFlow = flow.create('main', 'New Flow', (f) => {});\nmyFlow.start();")
    with open(workspace / "main.designer.ts", "w", encoding="utf-8") as f:
        f.write("import { flow, Message, Custom, JS, Global, Flow, Credential, AI } from '@robomotion/sdk';\n\nconst myFlow = flow.create('main', 'New Flow', (f) => {});\nmyFlow.start();")
        
    with open(workspace / ".env", "w", encoding="utf-8") as f:
        f.write(f"GITHUB_USERNAME={username}\nGITHUB_PAT={pat}\nGITHUB_REPO={repo_url}\n")
        
    repo_clean = repo_url.replace("https://", "")
    safe_username = urllib.parse.quote(username)
    auth_url = f"https://{safe_username}:{pat}@{repo_clean}"
    
    cflags = subprocess.CREATE_NO_WINDOW if os.name == 'nt' else 0
    
    print("[*] Initializing Git repository and pushing...")
    if not (workspace / '.git').exists():
        subprocess.run(['git', 'init'], cwd=workspace, check=True, creationflags=cflags)
        
    subprocess.run(['git', 'add', '.'], cwd=workspace, check=True, creationflags=cflags)
    subprocess.run(['git', 'commit', '-m', 'Workspace initialization via LLB CLI'], cwd=workspace, capture_output=True, creationflags=cflags)
    subprocess.run(['git', 'remote', 'remove', 'origin'], cwd=workspace, capture_output=True, creationflags=cflags)
    subprocess.run(['git', 'remote', 'add', 'origin', auth_url], cwd=workspace, check=True, creationflags=cflags)
    subprocess.run(['git', 'branch', '-M', 'main'], cwd=workspace, check=True, creationflags=cflags)
    subprocess.run(['git', 'push', '-u', 'origin', 'main'], cwd=workspace, check=True, creationflags=cflags)
    
    print("\n✅ Success! Workspace generated and synced to GitHub.")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Local LLM to Robomotion Bridge (CLI)")
    parser.add_argument("-p", "--project", required=True, help="Project name (Folder & Repo)")
    parser.add_argument("-u", "--username", required=True, help="GitHub Username")
    parser.add_argument("-t", "--pat", required=True, help="GitHub PAT Token")
    
    args = parser.parse_args()
    setup_workspace(args.project, args.username, args.pat)
