# ==============================================================================
# Local LLM to Robomotion Bridge (CLI Version)
# Copyright (C) 2026 Thexoxo (https://github.com/Thexoxo)
# YouTube: https://www.youtube.com/@xoxoPwn
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License.
# ==============================================================================

import os
import subprocess
import shutil
import json
import urllib.request
import urllib.error
import urllib.parse
import argparse
from pathlib import Path

# --- PROMPT AGENT ---
AGENT_PROMPT = """# SYSTEM INSTRUCTIONS: EXPERT DEVELOPER ROBOMOTION RPA

[CONTEXT AND ROLE]
You are an elite development agent for Robomotion RPA. Your mission is to design from scratch, modify, and deploy a 100% autonomous automation flow in this local workspace. You will generate the required 'main.ts' and 'main.designer.ts' files, then push them to the remote Git repository so they appear on the online Designer.

[STEP 1: SIMULTANEOUS LEARNING (MANDATORY)]
Before writing any code, you must deeply analyze the official SDK documentation, grammar, and design patterns stored locally on this machine at the following exact path:
"./skills-fallback/skills/creating-flow/docs/"

[STEP 2: IRON LAWS OF SYNTAX (STRICT COMPLIANCE REQUIRED)]
For the code to be valid and accepted by Robomotion, you must apply these 5 laws:
1. COMPLETE LINE 1: The 'main.ts' file must strictly start with the following exact import:
import { flow, Message, Custom, JS, Global, Flow, Credential, AI } from '@robomotion/sdk';

2. HEX-6 NODE IDs: All node identifiers (node IDs) in the flow must be 6-character lowercase hexadecimal strings (e.g., '42ec21', '7dbafc'). It is strictly FORBIDDEN to use plain text (like 'begin', 'loop', 'label').

3. PROPERTY ENCAPSULATION: Never pass raw primitive values to node options. Always use the Custom('value') or Message('variable') helpers (Example: optTimeout: Custom('30')).

4. LOOP PATTERNS: Strictly apply the structure: Label (Hex-6 ID) -> ForEach -> [Code Body] -> GoTo (the GoTo must explicitly jump to the Hex-6 ID of the Label node).

5. DATA TABLE FORMAT: For any data manipulation (CSV, Excel), the msg.table property must strictly follow this JSON object structure: { columns: [...], rows: [...] }.

[STEP 3: DEPLOYMENT AND AUTO-PUSH PROCESS]
Once you have written the 'main.ts' and 'main.designer.ts' files without errors, you are authorized to open the system terminal to autonomously execute the following sequence of Git commands to publish the flow to the Cloud:
1. git add .
2. git commit -m "Automated workflow generation and sync by AI Agent"
3. git push origin main

[YOUR MISSION]
Design the complete 'main.ts' and 'main.designer.ts' files, validate them, then execute the Auto-Push process for the following action:
--> [WRITE YOUR SPECIFIC GOAL HERE, EX: A robot that logs into a site, scrapes a data table, and saves it as CSV] <--
"""

def create_github_repo(username, pat, repo_name):
    url = "https://api.github.com/user/repos"
    headers = {
        "Authorization": f"Bearer {pat}",
        "Accept": "application/vnd.github.v3+json",
        "User-Agent": "Local-LLM-to-Robomotion-Bridge"
    }
    data = {
        "name": repo_name,
        "private": True,
        "description": "RPA Workspace generated by Local-LLM-to-Robomotion Bridge"
    }
    
    req = urllib.request.Request(url, data=json.dumps(data).encode("utf-8"), headers=headers, method="POST")
    try:
        with urllib.request.urlopen(req) as response:
            res_data = json.loads(response.read().decode())
            return res_data["clone_url"]
    except urllib.error.HTTPError as e:
        if e.code == 422:
            return f"https://github.com/{username}/{repo_name}.git"
        raise Exception(f"GitHub API Error: {e.code} - {e.reason}")

def setup_workspace(project_name, username, pat):
    project_name_clean = project_name.replace(" ", "-")
    
    print(f"[*] Contacting GitHub API to create repository '{project_name_clean}'...")
    try:
        repo_url = create_github_repo(username, pat, project_name_clean)
        print(f"[+] Repository ready: {repo_url}")
    except Exception as e:
        print(f"[!] Error creating GitHub repository: {e}")
        return

    desktop = Path(os.path.expanduser("~")) / "Desktop"
    workspace = desktop / project_name_clean
    script_dir = Path(__file__).parent
    source_docs = script_dir / 'skills-fallback'
    
    workspace.mkdir(parents=True, exist_ok=True)
    print(f"[*] Created local workspace at: {workspace}")
    
    dest_skills = workspace / "skills-fallback"
    if source_docs.exists() and not dest_skills.exists():
        shutil.copytree(source_docs, dest_skills)
        print("[+] Copied Robomotion documentation (skills-fallback).")
    elif not source_docs.exists():
        print("[!] Warning: 'skills-fallback' folder not found. AI will lack documentation.")
        
    with open(workspace / "agent_rules.md", "w", encoding="utf-8") as f:
        f.write(AGENT_PROMPT)
    print("[+] Created agent_rules.md")
        
    with open(workspace / "main.ts", "w", encoding="utf-8") as f:
        f.write("import { flow, Message, Custom, JS, Global, Flow, Credential, AI } from '@robomotion/sdk';\n\nconst myFlow = flow.create('main', 'New Flow', (f) => {});\nmyFlow.start();")
    with open(workspace / "main.designer.ts", "w", encoding="utf-8") as f:
        f.write("import { flow, Message, Custom, JS, Global, Flow, Credential, AI } from '@robomotion/sdk';\n\nconst myFlow = flow.create('main', 'New Flow', (f) => {});\nmyFlow.start();")
        
    with open(workspace / ".env", "w", encoding="utf-8") as f:
        f.write(f"GITHUB_USERNAME={username}\nGITHUB_PAT={pat}\nGITHUB_REPO={repo_url}\n")
        
    repo_clean = repo_url.replace("https://", "")
    safe_username = urllib.parse.quote(username)
    auth_url = f"https://{safe_username}:{pat}@{repo_clean}"
    
    cflags = subprocess.CREATE_NO_WINDOW if os.name == 'nt' else 0
    
    print("[*] Initializing Git repository and pushing...")
    if not (workspace / '.git').exists():
        subprocess.run(['git', 'init'], cwd=workspace, check=True, creationflags=cflags)
        
    subprocess.run(['git', 'add', '.'], cwd=workspace, check=True, creationflags=cflags)
    subprocess.run(['git', 'commit', '-m', 'Workspace initialization via LLB CLI'], cwd=workspace, capture_output=True, creationflags=cflags)
    subprocess.run(['git', 'remote', 'remove', 'origin'], cwd=workspace, capture_output=True, creationflags=cflags)
    subprocess.run(['git', 'remote', 'add', 'origin', auth_url], cwd=workspace, check=True, creationflags=cflags)
    subprocess.run(['git', 'branch', '-M', 'main'], cwd=workspace, check=True, creationflags=cflags)
    subprocess.run(['git', 'push', '-u', 'origin', 'main'], cwd=workspace, check=True, creationflags=cflags)
    
    print("\n✅ Success! Workspace generated and synced to GitHub.")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Local LLM to Robomotion Bridge (CLI)")
    parser.add_argument("-p", "--project", required=True, help="Project name (Folder & Repo)")
    parser.add_argument("-u", "--username", required=True, help="GitHub Username")
    parser.add_argument("-t", "--pat", required=True, help="GitHub PAT Token")
    
    args = parser.parse_args()
    setup_workspace(args.project, args.username, args.pat)
