# ==============================================================================
# Local LLM to Robomotion Bridge
# Copyright (C) 2026 Thexoxo (https://github.com/Thexoxo)
# YouTube: https://www.youtube.com/@xoxoPwn
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License.
# ==============================================================================

import tkinter as tk
from tkinter import messagebox
import os
import subprocess
import shutil
from pathlib import Path
import webbrowser
import json
import urllib.request
import urllib.error

# --- PROMPT AGENT ---
AGENT_PROMPT = """# SYSTEM INSTRUCTIONS: EXPERT DEVELOPER ROBOMOTION RPA

[CONTEXT AND ROLE]
You are an elite development agent for Robomotion RPA. Your mission is to design from scratch, modify, and deploy a 100% autonomous automation flow in this local workspace. You will generate the required 'main.ts' and 'main.designer.ts' files, then push them to the remote Git repository so they appear on the online Designer.

[STEP 1: SIMULTANEOUS LEARNING (MANDATORY)]
Before writing any code, you must deeply analyze the official SDK documentation, grammar, and design patterns stored locally on this machine at the following exact path:
"./skills-fallback/skills/creating-flow/docs/"

[STEP 2: IRON LAWS OF SYNTAX (STRICT COMPLIANCE REQUIRED)]
For the code to be valid and accepted by Robomotion, you must apply these 5 laws:
1. COMPLETE LINE 1: The 'main.ts' file must strictly start with the following exact import:
import { flow, Message, Custom, JS, Global, Flow, Credential, AI } from '@robomotion/sdk';

2. HEX-6 NODE IDs: All node identifiers (node IDs) in the flow must be 6-character lowercase hexadecimal strings (e.g., '42ec21', '7dbafc'). It is strictly FORBIDDEN to use plain text (like 'begin', 'loop', 'label').

3. PROPERTY ENCAPSULATION: Never pass raw primitive values to node options. Always use the Custom('value') or Message('variable') helpers (Example: optTimeout: Custom('30')).

4. LOOP PATTERNS: Strictly apply the structure: Label (Hex-6 ID) -> ForEach -> [Code Body] -> GoTo (the GoTo must explicitly jump to the Hex-6 ID of the Label node).

5. DATA TABLE FORMAT: For any data manipulation (CSV, Excel), the msg.table property must strictly follow this JSON object structure: { columns: [...], rows: [...] }.

[STEP 3: DEPLOYMENT AND AUTO-PUSH PROCESS]
Once you have written the 'main.ts' and 'main.designer.ts' files without errors, you are authorized to open the system terminal to autonomously execute the following sequence of Git commands to publish the flow to the Cloud:
1. git add .
2. git commit -m "Automated workflow generation and sync by AI Agent"
3. git push origin main

[YOUR MISSION]
Design the complete 'main.ts' and 'main.designer.ts' files, validate them, then execute the Auto-Push process for the following action:
--> [WRITE YOUR SPECIFIC GOAL HERE, EX: A robot that logs into a site, scrapes a data table, and saves it as CSV] <--
"""

def create_github_repo(username, pat, repo_name):
    url = "https://api.github.com/user/repos"
    headers = {
        "Authorization": f"Bearer {pat}",
        "Accept": "application/vnd.github.v3+json",
        "User-Agent": "Local-LLM-to-Robomotion-Bridge"
    }
    data = {
        "name": repo_name,
        "private": True,
        "description": "RPA Workspace generated by Local-LLM-to-Robomotion Bridge"
    }
    
    req = urllib.request.Request(url, data=json.dumps(data).encode("utf-8"), headers=headers, method="POST")
    try:
        with urllib.request.urlopen(req) as response:
            res_data = json.loads(response.read().decode())
            return res_data["clone_url"]
    except urllib.error.HTTPError as e:
        # 422 means repository already exists, which is fine, we just return the presumed URL
        if e.code == 422:
            return f"https://github.com/{username}/{repo_name}.git"
        raise Exception(f"GitHub API Error: {e.code} - {e.reason}")

def setup_workspace():
    username = entry_user.get().strip()
    pat = entry_pat.get().strip()
    project_name = entry_proj.get().strip()
    
    if not username or not pat or not project_name:
        messagebox.showerror("Error", "All fields are required.")
        return
        
    try:
        import urllib.parse
        
        project_name_clean = project_name.replace(" ", "-")
        
        # 0. Magically create the repository on GitHub
        messagebox.showinfo("Processing", "Contacting GitHub API to create repository...")
        repo_url = create_github_repo(username, pat, project_name_clean)
        
        # Paths definition
        desktop = Path(os.path.expanduser("~")) / "Desktop"
        workspace = desktop / project_name_clean
        
        script_dir = Path(__file__).parent
        source_docs = script_dir / 'skills-fallback'
        
        workspace.mkdir(parents=True, exist_ok=True)
        
        dest_skills = workspace / "skills-fallback"
        if source_docs.exists() and not dest_skills.exists():
            shutil.copytree(source_docs, dest_skills)
        elif not source_docs.exists():
            messagebox.showwarning("Warning", "The 'skills-fallback' folder was not found next to the installer. The AI will lack documentation.")
            
        with open(workspace / "agent_rules.md", "w", encoding="utf-8") as f:
            f.write(AGENT_PROMPT)
            
        with open(workspace / "main.ts", "w", encoding="utf-8") as f:
            f.write("import { flow, Message, Custom, JS, Global, Flow, Credential, AI } from '@robomotion/sdk';\n\nconst myFlow = flow.create('main', 'New Flow', (f) => {});\nmyFlow.start();")
        with open(workspace / "main.designer.ts", "w", encoding="utf-8") as f:
            f.write("import { flow, Message, Custom, JS, Global, Flow, Credential, AI } from '@robomotion/sdk';\n\nconst myFlow = flow.create('main', 'New Flow', (f) => {});\nmyFlow.start();")
            
        with open(workspace / ".env", "w", encoding="utf-8") as f:
            f.write(f"GITHUB_USERNAME={username}\nGITHUB_PAT={pat}\nGITHUB_REPO={repo_url}\n")
            
        repo_clean = repo_url.replace("https://", "")
        # URL encode the username to prevent issues if user inputs an email address
        safe_username = urllib.parse.quote(username)
        # Using only PAT as credentials often bypasses Git Credential Manager issues
        auth_url = f"https://{safe_username}:{pat}@{repo_clean}"
        
        cflags = subprocess.CREATE_NO_WINDOW if os.name == 'nt' else 0
        if not (workspace / '.git').exists():
            subprocess.run(['git', 'init'], cwd=workspace, check=True, creationflags=cflags)
            
        subprocess.run(['git', 'add', '.'], cwd=workspace, check=True, creationflags=cflags)
        subprocess.run(['git', 'commit', '-m', 'Workspace initialization via GitHub API'], cwd=workspace, capture_output=True, creationflags=cflags)
        subprocess.run(['git', 'remote', 'remove', 'origin'], cwd=workspace, capture_output=True, creationflags=cflags)
        subprocess.run(['git', 'remote', 'add', 'origin', auth_url], cwd=workspace, check=True, creationflags=cflags)
        subprocess.run(['git', 'branch', '-M', 'main'], cwd=workspace, check=True, creationflags=cflags)
        subprocess.run(['git', 'push', '-u', 'origin', 'main'], cwd=workspace, check=True, creationflags=cflags)
        
        msg = (f"✅ Workspace '{project_name}' successfully created!\n"
               f"✅ GitHub Repository '{project_name}' automatically created via API.\n\n"
               "Please read the README.md file to know how to pilot your AI.")
        messagebox.showinfo("Success", msg)
        root.destroy()
        
    except Exception as e:
        messagebox.showerror("Error", f"An error occurred:\n{str(e)}")

def open_youtube():
    webbrowser.open("https://www.youtube.com/@xoxoPwn")

def open_github():
    webbrowser.open("https://github.com/Thexoxo")

# --- UI ---
root = tk.Tk()
root.title("Local LLM to Robomotion Bridge")
root.geometry("600x560")
root.configure(padx=20, pady=20)
root.resizable(False, False)

tk.Label(root, text="Local LLM to Robomotion Bridge", font=("Helvetica", 14, "bold")).pack(pady=(0, 10))

frame = tk.Frame(root)
frame.pack(fill="x")

tk.Label(frame, text="Project Name (Folder & Repo):").grid(row=0, column=0, sticky="w", pady=5)
entry_proj = tk.Entry(frame, width=45)
entry_proj.grid(row=0, column=1, pady=5, padx=5)
entry_proj.insert(0, "my_rpa_workspace")

tk.Label(frame, text="GitHub Username:").grid(row=1, column=0, sticky="w", pady=5)
entry_user = tk.Entry(frame, width=45)
entry_user.grid(row=1, column=1, pady=5, padx=5)

tk.Label(frame, text="PAT Token (Key):").grid(row=2, column=0, sticky="w", pady=5)
entry_pat = tk.Entry(frame, width=45, show="*")
entry_pat.grid(row=2, column=1, pady=5, padx=5)

tk.Button(root, text="🔥 Auto-Create Repo & Generate Workspace", bg="#2c3e50", fg="white", font=("Helvetica", 11, "bold"), command=setup_workspace).pack(pady=15)

# --- HOW TO USE (ENGLISH) ---
instructions_frame = tk.LabelFrame(root, text=" 📖 How to use this tool? (Tutorial) ", font=("Helvetica", 10, "bold"), padx=15, pady=15)
instructions_frame.pack(fill="both", expand=True, pady=10)

instructions_text = """Step 1: Generate a GitHub PAT (Classic Token) with 'repo' 
permissions enabled! Then, fill out the fields above. The software 
will auto-create a private repository using the API.

Step 2: Open your local LLM / AI Agent (Anti Gravity, LM Studio) 
in the generated folder on your Desktop. Give it the prompt: 
"Read agent_rules.md and build the automation flow."

Step 3: AUTO-SYNC! Let the AI write the code. This script 
will automatically push the generated code directly to GitHub.

Step 4: Go to Robomotion Designer -> Click 'Import Flow' -> 'From Git'.
⚠️ IMPORTANT - Fill the fields EXACTLY like this:
- Git URL: https://github.com/Username/Project-Name.git
- Branch: main
- Authentication Token: Your GitHub PAT"""

tk.Label(instructions_frame, text=instructions_text, justify="left", font=("Consolas", 9), fg="#333333").pack(anchor="w")

links_frame = tk.Frame(root)
links_frame.pack(side="bottom", fill="x", pady=5)

tk.Button(links_frame, text="▶️ YouTube", command=open_youtube, cursor="hand2", bg="#ff0000", fg="white", font=("Helvetica", 9, "bold")).pack(side="left", padx=10)
tk.Button(links_frame, text="🐙 GitHub", command=open_github, cursor="hand2", bg="#333333", fg="white", font=("Helvetica", 9, "bold")).pack(side="left", padx=10)

signature = tk.Label(links_frame, text="Made with 🌍 ❤️ by xoxo", font=("Helvetica", 9, "italic"), fg="#666666")
signature.pack(side="right", padx=10)

root.mainloop()
